# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build
    jobs:
      - job: 
        displayName: "Build"
        steps:
          
          
          - task: SonarCloudPrepare@2
            inputs:
              SonarCloud: 'mysonarcloud'
              organization: 'mysonarcloud280'
              scannerMode: 'Other'
              extraProperties: |
                # Additional properties that will be passed to the scanner,
                # Put one key=value per line, example:
                # sonar.exclusions=**/*.bin
                sonar.projectKey=sivabalaji280_tweettrend
                sonar.projectName=tweettrend
          - task: Maven@4
            inputs:
              mavenPomFile: 'pom.xml'
              goals: 'clean deploy'
              publishJUnitResults: true
              testResultsFiles: '**/surefire-reports/TEST-*.xml'
              javaHomeOption: 'JDKVersion'
              mavenVersionOption: 'Default'
              mavenAuthenticateFeed: false
              effectivePomSkip: false
              sonarQubeRunAnalysis: false
          - task: SonarCloudPublish@2
            inputs:
              pollingTimeoutSec: '300'
          

        
           
